### PR TITLE
added Armstrong program

### PR DESCRIPTION
**Pull request by SHARMA-SAURAV**
Armstrong program using python

### CODE REVIEW

**Comment by SHARMA-SAURAV** [comment]
sir please chesk it and kindly add to hactoberfest event

**Comment by ajay946** [comment]
Hey Saurav, I have no idea about the event. Please tell me about it.

>

**Comment by SHARMA-SAURAV** [comment]
https://hacktoberfest.digitalocean.com/ please register here with your github id and merge my pull request.
Hacktoberfest 2020 is a month long virtual festival event to celebrate open source contributions presented by Digital Ocean, Intel and DEV. It is the easiest way to get into open source.By participating here you can win a cool shirt from digital ocean Labelled with hacktoberfest label.

**Review by ajay946 — APPROVED** [review]

**Comment by SHARMA-SAURAV** [comment]
please register first after accept it then this repository will not be count in hactoberfest event

**Pull request merged**
